"""add user_group_preferences and user_dm_preferences

Revision ID: 1ed66a7072ff
Revises: f0g1h2i3j4k5
Create Date: 2026-07-29 08:42:15.744865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ed66a7072ff'
down_revision: Union[str, None] = 'f0g1h2i3j4k5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_group_pref')
    )
    op.create_table('user_dm_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('is_special_care', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['dm_sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_id', name='uq_user_dm_pref')
    )
    op.drop_table('agent_alarms')
    op.drop_table('structured_records')
    op.drop_table('agent_workspace')
    op.drop_index('idx_file_metadata_owner', table_name='file_metadata')
    op.drop_index('idx_group_invitations_group', table_name='group_invitations')
    op.drop_index('idx_group_invitations_invitee', table_name='group_invitations')
    op.alter_column('system_logs', 'log_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='操作类型: config|user|ai|api|file|permission|system')
    op.alter_column('system_logs', 'operator_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               comment='操作者类型: human|ai|system')
    op.alter_column('system_logs', 'operator_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='操作者 ID')
    op.alter_column('system_logs', 'target_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='操作目标类型')
    op.alter_column('system_logs', 'target_id',
               existing_type=sa.INTEGER(),
               comment='操作目标 ID',
               existing_nullable=True)
    op.alter_column('system_logs', 'success',
               existing_type=sa.BOOLEAN(),
               comment='操作成功/失败',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('system_logs', 'error_message',
               existing_type=sa.TEXT(),
               comment='失败原因',
               existing_nullable=True)
    op.alter_column('system_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='客户端 IP（IPv4/IPv6）',
               existing_nullable=True)
    op.alter_column('system_logs', 'old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='变更前值',
               existing_nullable=True)
    op.alter_column('system_logs', 'new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='变更后值',
               existing_nullable=True)
    op.alter_column('system_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='其他上下文',
               existing_nullable=True)
    op.alter_column('system_logs', 'prev_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='上一条日志的 SHA256',
               existing_nullable=True)
    op.alter_column('system_logs', 'hash',
               existing_type=sa.VARCHAR(length=64),
               comment='本条日志的 SHA256（含 prev_hash）',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('system_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               comment='记录时间',
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_table_comment(
        'system_logs',
        '审计日志（哈希链防篡改）',
        existing_comment=None,
        schema=None
    )
    op.alter_column('system_settings', 'registration_enabled',
               existing_type=sa.BOOLEAN(),
               comment='是否开放注册通道（默认开启）',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('system_settings', 'geoip_provider_url',
               existing_type=sa.VARCHAR(length=512),
               comment='IP 地理位置查询后端 URL，含 {ip} 占位符，留空默认 http://ip-api.com/json/{ip}',
               existing_nullable=True)
    op.alter_column('system_settings', 'audit_user_actions',
               existing_type=sa.BOOLEAN(),
               comment='是否记录用户行为日志（登录、发消息等），默认关闭',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('system_settings', 'audit_log_retention_days',
               existing_type=sa.INTEGER(),
               comment='审计日志保留天数，超期自动清理（默认 90 天）',
               existing_nullable=True,
               existing_server_default=sa.text('90'))
    op.alter_column('system_settings', 'message_retention_days',
               existing_type=sa.INTEGER(),
               comment='消息保留天数（0=永久保留）',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最近在线时间，NULL=当前在线',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='最近在线时间，NULL=当前在线',
               existing_nullable=True)
    op.alter_column('system_settings', 'message_retention_days',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='消息保留天数（0=永久保留）',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('system_settings', 'audit_log_retention_days',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='审计日志保留天数，超期自动清理（默认 90 天）',
               existing_nullable=True,
               existing_server_default=sa.text('90'))
    op.alter_column('system_settings', 'audit_user_actions',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否记录用户行为日志（登录、发消息等），默认关闭',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('system_settings', 'geoip_provider_url',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='IP 地理位置查询后端 URL，含 {ip} 占位符，留空默认 http://ip-api.com/json/{ip}',
               existing_nullable=True)
    op.alter_column('system_settings', 'registration_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否开放注册通道（默认开启）',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_table_comment(
        'system_logs',
        existing_comment='审计日志（哈希链防篡改）',
        schema=None
    )
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.alter_column('system_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='记录时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('system_logs', 'hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='本条日志的 SHA256（含 prev_hash）',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('system_logs', 'prev_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='上一条日志的 SHA256',
               existing_nullable=True)
    op.alter_column('system_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='其他上下文',
               existing_nullable=True)
    op.alter_column('system_logs', 'new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='变更后值',
               existing_nullable=True)
    op.alter_column('system_logs', 'old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='变更前值',
               existing_nullable=True)
    op.alter_column('system_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='客户端 IP（IPv4/IPv6）',
               existing_nullable=True)
    op.alter_column('system_logs', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='失败原因',
               existing_nullable=True)
    op.alter_column('system_logs', 'success',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='操作成功/失败',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('system_logs', 'target_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='操作目标 ID',
               existing_nullable=True)
    op.alter_column('system_logs', 'target_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='操作目标类型')
    op.alter_column('system_logs', 'operator_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='操作者 ID')
    op.alter_column('system_logs', 'operator_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               comment=None,
               existing_comment='操作者类型: human|ai|system')
    op.alter_column('system_logs', 'log_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='操作类型: config|user|ai|api|file|permission|system')
    op.create_index('idx_group_invitations_invitee', 'group_invitations', ['invitee_id', 'status'], unique=False)
    op.create_index('idx_group_invitations_group', 'group_invitations', ['group_id'], unique=False)
    op.create_index('idx_file_metadata_owner', 'file_metadata', ['owner_type', 'owner_id'], unique=False)
    op.create_table('agent_workspace',
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_task', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_task_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('interrupted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('interruption_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('todo', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('plan', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('journal', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='agent_workspace_agent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', name='agent_workspace_pkey')
    )
    op.create_table('structured_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sub_key', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('field', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='structured_records_agent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='structured_records_pkey'),
    sa.UniqueConstraint('agent_id', 'category', 'sub_key', 'field', name='structured_records_agent_id_category_sub_key_field_key')
    )
    op.create_table('agent_alarms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wake_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('task', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('fired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'fired'::character varying, 'cancelled'::character varying]::text[])", name='agent_alarms_status_check'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='agent_alarms_agent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='agent_alarms_pkey')
    )
    op.drop_table('user_dm_preferences')
    op.drop_table('user_group_preferences')
    # ### end Alembic commands ###
