"""add last_cleanup_stats to system_settings

Revision ID: 20efaf9a57ca
Revises: b0b1b2b3b4b5
Create Date: 2026-07-29 11:00:36.631260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20efaf9a57ca'
down_revision: Union[str, None] = 'b0b1b2b3b4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_workspace')
    op.drop_table('agent_alarms')
    op.drop_table('structured_records')
    op.drop_index('idx_file_metadata_owner', table_name='file_metadata')
    op.drop_index('idx_group_invitations_group', table_name='group_invitations')
    op.drop_index('idx_group_invitations_invitee', table_name='group_invitations')
    op.add_column('system_settings', sa.Column('last_cleanup_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='上次清理统计：{cleaned_files, cleaned_refs, orphan_cleaned, run_at}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'last_cleanup_stats')
    op.create_index('idx_group_invitations_invitee', 'group_invitations', ['invitee_id', 'status'], unique=False)
    op.create_index('idx_group_invitations_group', 'group_invitations', ['group_id'], unique=False)
    op.create_index('idx_file_metadata_owner', 'file_metadata', ['owner_type', 'owner_id'], unique=False)
    op.create_table('structured_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sub_key', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('field', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='structured_records_agent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='structured_records_pkey'),
    sa.UniqueConstraint('agent_id', 'category', 'sub_key', 'field', name='uq_sr_path')
    )
    op.create_table('agent_alarms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wake_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('task', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('fired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying::text, 'fired'::character varying::text, 'cancelled'::character varying::text])", name='agent_alarms_status_check'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='agent_alarms_agent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='agent_alarms_pkey')
    )
    op.create_table('agent_workspace',
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_task', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_task_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('interrupted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('interruption_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('todo', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('plan', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('journal', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='agent_workspace_agent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', name='agent_workspace_pkey')
    )
    # ### end Alembic commands ###
