"""feat: 新增5张表 + 对齐模型与数据库差异

Revision ID: a5ceafb69c41
Revises: e7f8g9h0i1j2
Create Date: 2026-07-24 06:00:03.518070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5ceafb69c41'
down_revision: Union[str, None] = 'e7f8g9h0i1j2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_attention',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('interested_topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('interested_users', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('interested_patterns', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('ignored_topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('ignored_patterns', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('match_action', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('config_type', sa.String(length=20), nullable=True),
    sa.Column('config_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_skill_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'skill_name', name='uq_agent_skill')
    )
    op.create_table('agent_state_stack',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('frame_type', sa.String(length=50), nullable=False),
    sa.Column('context_ref', sa.String(length=100), nullable=True),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('doing', sa.Text(), nullable=True),
    sa.Column('todo', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('journal', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_triggers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_fires', sa.Integer(), nullable=True),
    sa.Column('fire_count', sa.Integer(), nullable=True),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personality_anchors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('identity', sa.Text(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('core_values', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('structured_records')
    op.drop_table('agent_alarms')
    op.drop_table('agent_workspace')
    op.drop_constraint('agent_collaborators_agent_id_user_id_key', 'agent_collaborators', type_='unique')
    op.create_unique_constraint('uq_agent_collaborator', 'agent_collaborators', ['agent_id', 'user_id'])
    op.alter_column('agent_config_history', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agent_metrics', 'snapshot_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='指标快照数据',
               existing_nullable=False)
    op.alter_column('agent_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='快照时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_skills', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='技能名称，如「延迟回复」「温柔模式」',
               existing_nullable=False)
    op.alter_column('agent_skills', 'skill_type',
               existing_type=sa.VARCHAR(length=30),
               comment='delay_reply | typing_indicator | scene_trigger | inject_prompt',
               existing_nullable=False)
    op.alter_column('agent_skills', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('agent_skills', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='技能配置JSON，各type不同schema',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_skills', 'priority',
               existing_type=sa.INTEGER(),
               comment='优先级：数字越大越靠后',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_agent_skills_agent', table_name='agent_skills')
    op.alter_column('agent_user_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_user_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agents', 'config_profile',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'custom'::character varying"))
    op.alter_column('agents', 'api_credit_cost',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'delay_reply_enabled',
               existing_type=sa.BOOLEAN(),
               comment='延迟回复功能开关，NULL=继承全局默认',
               existing_nullable=True)
    op.alter_column('agents', 'max_tool_rounds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('agents', 'alarm_max_tool_rounds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('agents', 'force_alarm_on_end',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('agents', 'max_alarms',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('agents', 'reminder_grace',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'5m_after'::character varying"))
    op.alter_column('agents', 'hide_ai_identity',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('agents', 'allow_friend_requests',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='是否允许接收好友申请',
               existing_server_default=sa.text('true'))
    op.alter_column('agents', 'auto_respond_friend_request',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='收到好友申请时是否自动触发 API 响应',
               existing_server_default=sa.text('false'))
    op.alter_column('agents', 'discoverable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='是否允许他人发现与查找此 AI',
               existing_server_default=sa.text('true'))
    op.alter_column('agents', 'ai_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'resonance'::character varying"))
    op.alter_column('agents', 'allow_others_chat',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='是否允许非主人触发此 AI 对话',
               existing_server_default=sa.text('true'))
    op.alter_column('agents', 'others_chat_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='允许时的模式: unlimited | quota',
               existing_server_default=sa.text("'unlimited'::character varying"))
    op.alter_column('agents', 'others_chat_quota',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='配额上限（触发次数），仅 quota 模式生效',
               existing_server_default=sa.text('30'))
    op.alter_column('agents', 'others_chat_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='当前已使用次数（可重置）',
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'disallow_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='禁止时的模式: strict | own_key',
               existing_server_default=sa.text("'strict'::character varying"))
    op.alter_column('agents', 'auto_reset_quota',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='每次用户 DM 时自动重置配额计数',
               existing_server_default=sa.text('false'))
    op.alter_column('agents', 'quota_whitelist',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_comment='不消耗配额的白名单实体列表',
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agents', 'group_owner_pays',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='群聊中 AI 消息是否由群主付费',
               existing_server_default=sa.text('true'))
    op.alter_column('agents', 'memory_load_mode',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'index_only'::character varying"))
    op.alter_column('agents', 'memory_recent_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'memory_shared_scope',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'private_only'::character varying"))
    op.alter_column('agents', 'bio',
               existing_type=sa.TEXT(),
               comment='AI 简介',
               existing_nullable=True)
    op.alter_column('agents', 'status_text',
               existing_type=sa.VARCHAR(length=100),
               comment='自定义状态文本',
               existing_nullable=True)
    op.alter_column('agents', 'status_color',
               existing_type=sa.VARCHAR(length=20),
               comment='状态文字颜色(hex)',
               existing_nullable=True)
    op.drop_index('idx_conv_logs_agent', table_name='ai_conversation_logs')
    op.drop_index('idx_conv_logs_time', table_name='ai_conversation_logs')
    op.create_index(op.f('ix_ai_conversation_logs_agent_id'), 'ai_conversation_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_ai_conversation_logs_created_at'), 'ai_conversation_logs', ['created_at'], unique=False)
    op.alter_column('api_key_pool', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='管理员命名（如 DeepSeek 主号）',
               existing_nullable=False)
    op.alter_column('api_key_pool', 'api_base_url',
               existing_type=sa.TEXT(),
               comment='API 地址，NULL=继承全局',
               existing_nullable=True)
    op.alter_column('api_key_pool', 'api_key_encrypted',
               existing_type=sa.TEXT(),
               comment='Fernet 加密的 API Key',
               existing_nullable=False)
    op.alter_column('api_key_pool', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='管理员可禁用',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('api_key_pool', 'priority',
               existing_type=sa.INTEGER(),
               comment='越高越优先分配',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('api_key_pool', 'concurrent_limit',
               existing_type=sa.INTEGER(),
               comment='并发上限，NULL=按模型默认(pro=500,flash=2500)',
               existing_nullable=True)
    op.alter_column('api_key_pool', 'provider_name',
               existing_type=sa.VARCHAR(length=100),
               comment='关联 provider_config[].name，NULL=使用第一个/默认供应商',
               existing_nullable=True)
    op.alter_column('api_usage_log', 'user_id',
               existing_type=sa.INTEGER(),
               comment='哪个用户消耗的',
               existing_nullable=False)
    op.alter_column('api_usage_log', 'agent_id',
               existing_type=sa.INTEGER(),
               comment='哪个 AI 产生的调用',
               existing_nullable=True)
    op.alter_column('api_usage_log', 'pool_key_id',
               existing_type=sa.INTEGER(),
               comment='使用的池 Key（NULL=用户自有 Key）',
               existing_nullable=True)
    op.alter_column('api_usage_log', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment='来源：user_key | pool_key',
               existing_nullable=False,
               existing_server_default=sa.text("'user_key'::character varying"))
    op.alter_column('conversation_log_config', 'default_delay_reply_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('conversation_log_config', 'compression_threshold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('60'))
    op.alter_column('detail_memories', 'rough_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_dm_messages_created_at', table_name='dm_messages')
    op.drop_index('idx_dm_messages_session', table_name='dm_messages')
    op.drop_constraint('dm_sessions_user1_id_user2_id_key', 'dm_sessions', type_='unique')
    op.create_unique_constraint('uq_dm_session_users', 'dm_sessions', ['user1_id', 'user2_id'])
    op.drop_constraint('federated_entities_federated_id_key', 'federated_entities', type_='unique')
    op.drop_constraint('federated_entities_peer_id_entity_type_local_ref_id_key', 'federated_entities', type_='unique')
    op.create_index(op.f('ix_federated_entities_federated_id'), 'federated_entities', ['federated_id'], unique=True)
    op.create_unique_constraint('uq_fed_entity_peer_local', 'federated_entities', ['peer_id', 'entity_type', 'local_ref_id'])
    op.alter_column('federation_peers', 'shared_secret_encrypted',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('federation_peers', 'url_rotation_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint('file_collaborators_file_id_collaborator_type_collaborator_i_key', 'file_collaborators', type_='unique')
    op.drop_index('idx_file_collabs_file', table_name='file_collaborators')
    op.create_unique_constraint('uq_file_collab', 'file_collaborators', ['file_id', 'collaborator_type', 'collaborator_id'])
    op.alter_column('file_metadata', 'path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('file_metadata', 'owner_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('file_metadata', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_file_metadata_owner', table_name='file_metadata')
    op.drop_index('idx_file_metadata_path', table_name='file_metadata')
    op.drop_index('idx_file_refs_file', table_name='file_references')
    op.drop_index('idx_file_refs_ref', table_name='file_references')
    op.alter_column('friendship_requests', 'requester_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_fr_requester', table_name='friendship_requests')
    op.drop_index('idx_fr_target', table_name='friendship_requests')
    op.create_index(op.f('ix_friendship_requests_requester_id'), 'friendship_requests', ['requester_id'], unique=False)
    op.drop_constraint('friendship_requests_requester_id_fkey', 'friendship_requests', type_='foreignkey')
    op.alter_column('friendships', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('friendships_user_id_friend_type_friend_id_key', 'friendships', type_='unique')
    op.drop_index('idx_friends_user', table_name='friendships')
    op.create_index(op.f('ix_friendships_user_id'), 'friendships', ['user_id'], unique=False)
    op.create_unique_constraint('uq_friendship', 'friendships', ['user_id', 'friend_type', 'friend_id'])
    op.drop_constraint('friendships_user_id_fkey', 'friendships', type_='foreignkey')
    op.drop_index('idx_group_invitations_group', table_name='group_invitations')
    op.drop_index('idx_group_invitations_invitee', table_name='group_invitations')
    op.alter_column('group_message_embeddings', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('group_message_embeddings', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('groups', 'owner_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('groups', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('instance_config', 'github_token_encrypted',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('messages', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'sender_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_messages_created_at', table_name='messages')
    op.drop_index('idx_messages_group_id', table_name='messages')
    op.alter_column('opencli_command_whitelist', 'default_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_opencli_log_agent_time', table_name='opencli_usage_log')
    op.alter_column('pending_messages', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pending_messages', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pending_messages', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_pending_msg_agent', table_name='pending_messages')
    op.drop_index('idx_pending_msg_group', table_name='pending_messages')
    op.alter_column('redemption_codes', 'code_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'ai_quota'::character varying"))
    op.alter_column('redemption_codes', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('redemption_codes', 'note',
               existing_type=sa.TEXT(),
               comment='管理员备注（不暴露给用户）',
               existing_nullable=True)
    op.alter_column('redemption_codes', 'max_usage',
               existing_type=sa.INTEGER(),
               comment='此码最多可用多少 credit（NULL=一次性全额）',
               existing_nullable=True)
    op.alter_column('redemption_codes', 'is_api_pool',
               existing_type=sa.BOOLEAN(),
               comment='是否使用 API 池额度',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('rough_memories', 'owner_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('rough_memories', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rough_memories', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='active | pending_archive | discarded',
               existing_nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('rough_memories', 'value_score',
               existing_type=sa.INTEGER(),
               comment='记忆价值评分: 1=低价值(自动提取), 5=正常, 10=高价值',
               existing_nullable=True,
               existing_server_default=sa.text('5'))
    op.drop_index('idx_rough_memories_owner', table_name='rough_memories')
    op.drop_index('idx_system_logs_created_at', table_name='system_logs')
    op.drop_index('idx_system_logs_type', table_name='system_logs')
    op.alter_column('system_settings', 'default_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('system_settings', 'default_platform_credit',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='全局默认平台赠送额度（0=禁用）',
               existing_server_default=sa.text('0'))
    op.alter_column('system_settings', 'federation_sync_interval_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='联邦 profile 同步间隔（分钟），默认 720（12小时）',
               existing_server_default=sa.text('720'))
    op.alter_column('system_settings', 'orphan_retention_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='孤儿文件宽限期（天），到期自动物理删除',
               existing_server_default=sa.text('7'))
    op.alter_column('system_settings', 'default_file_quota_mb',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='新用户默认文件存储配额（MB）',
               existing_server_default=sa.text('100'))
    op.alter_column('system_settings', 'default_concurrent_ai_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='新建群聊默认 AI 并发数',
               existing_server_default=sa.text('3'))
    op.alter_column('system_settings', 'system_prompt_overrides',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='系统提示词覆盖（管理员自定义 core_identity/protocols 等段）',
               existing_nullable=True)
    op.alter_column('system_settings', 'system_prompt_order',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='系统提示词段拼接顺序（NULL=使用代码默认 SEGMENT_ORDER）',
               existing_nullable=True)
    op.alter_column('system_settings', 'smtp_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='SMTP 邮件配置（密码 Fernet 加密）',
               existing_nullable=True)
    op.alter_column('system_settings', 'email_templates',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='自定义邮件模板（含预设选择：gradient/simple/custom）',
               existing_nullable=True)
    op.alter_column('system_settings', 'provider_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='LLM 厂商预设：{provider, base_url, chat_model, work_model, embedding_model, model_options}',
               existing_nullable=True)
    op.alter_column('system_settings', 'require_email_verification',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='注册是否必须验证邮箱（默认关闭）',
               existing_server_default=sa.text('false'))
    op.alter_column('system_settings', 'login_providers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               comment='可用登录方式: direct/email_code/wechat/qq',
               existing_server_default=sa.text('\'["direct"]\'::jsonb'))
    op.alter_column('unread_summary_cache', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('unread_summary_cache', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_summary_cache_lookup', table_name='unread_summary_cache')
    op.alter_column('users', 'api_credit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'platform_gifted_credit',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='平台赠送额度（独立于兑换码额度）',
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'agent_bundle_credit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'file_quota_mb',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('users', 'file_quota_bonus_mb',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='兑换码累积的额外配额',
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'status_text',
               existing_type=sa.VARCHAR(length=100),
               comment='自定义状态文本',
               existing_nullable=True)
    op.alter_column('users', 'status_color',
               existing_type=sa.VARCHAR(length=20),
               comment='状态文字颜色(hex)',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='用户邮箱，全局唯一（NULL 不受唯一约束）',
               existing_nullable=True)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='邮箱是否已验证',
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'setup_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_users_email_unique', table_name='users', postgresql_where='(email IS NOT NULL)')
    op.alter_column('vector_acceleration_requests', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vector_acceleration_requests', 'requester_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('verification_codes', 'code',
               existing_type=sa.VARCHAR(length=10),
               comment='6 位数字验证码',
               existing_nullable=False)
    op.alter_column('verification_codes', 'purpose',
               existing_type=sa.VARCHAR(length=30),
               comment='register / login / rebind',
               existing_nullable=False)
    op.alter_column('verification_codes', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('verification_codes', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='请求者 IP（用于频率限制）',
               existing_nullable=True)
    op.alter_column('verification_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_vc_email_purpose', table_name='verification_codes')
    op.drop_index('idx_vc_expires', table_name='verification_codes')
    op.create_index(op.f('ix_verification_codes_email'), 'verification_codes', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_codes_email'), table_name='verification_codes')
    op.create_index('idx_vc_expires', 'verification_codes', ['expires_at'], unique=False)
    op.create_index('idx_vc_email_purpose', 'verification_codes', ['email', 'purpose'], unique=False)
    op.alter_column('verification_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('verification_codes', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='请求者 IP（用于频率限制）',
               existing_nullable=True)
    op.alter_column('verification_codes', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('verification_codes', 'purpose',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='register / login / rebind',
               existing_nullable=False)
    op.alter_column('verification_codes', 'code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='6 位数字验证码',
               existing_nullable=False)
    op.alter_column('vector_acceleration_requests', 'requester_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vector_acceleration_requests', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('idx_users_email_unique', 'users', ['email'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.alter_column('users', 'setup_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='邮箱是否已验证',
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='用户邮箱，全局唯一（NULL 不受唯一约束）',
               existing_nullable=True)
    op.alter_column('users', 'status_color',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='状态文字颜色(hex)',
               existing_nullable=True)
    op.alter_column('users', 'status_text',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='自定义状态文本',
               existing_nullable=True)
    op.alter_column('users', 'file_quota_bonus_mb',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='兑换码累积的额外配额',
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'file_quota_mb',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('users', 'agent_bundle_credit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'platform_gifted_credit',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='平台赠送额度（独立于兑换码额度）',
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'api_credit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index('idx_summary_cache_lookup', 'unread_summary_cache', ['agent_id', 'group_id', 'expires_at'], unique=False)
    op.alter_column('unread_summary_cache', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('unread_summary_cache', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('system_settings', 'login_providers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               comment=None,
               existing_comment='可用登录方式: direct/email_code/wechat/qq',
               existing_server_default=sa.text('\'["direct"]\'::jsonb'))
    op.alter_column('system_settings', 'require_email_verification',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='注册是否必须验证邮箱（默认关闭）',
               existing_server_default=sa.text('false'))
    op.alter_column('system_settings', 'provider_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='LLM 厂商预设：{provider, base_url, chat_model, work_model, embedding_model, model_options}',
               existing_nullable=True)
    op.alter_column('system_settings', 'email_templates',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='自定义邮件模板（含预设选择：gradient/simple/custom）',
               existing_nullable=True)
    op.alter_column('system_settings', 'smtp_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='SMTP 邮件配置（密码 Fernet 加密）',
               existing_nullable=True)
    op.alter_column('system_settings', 'system_prompt_order',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='系统提示词段拼接顺序（NULL=使用代码默认 SEGMENT_ORDER）',
               existing_nullable=True)
    op.alter_column('system_settings', 'system_prompt_overrides',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='系统提示词覆盖（管理员自定义 core_identity/protocols 等段）',
               existing_nullable=True)
    op.alter_column('system_settings', 'default_concurrent_ai_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='新建群聊默认 AI 并发数',
               existing_server_default=sa.text('3'))
    op.alter_column('system_settings', 'default_file_quota_mb',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='新用户默认文件存储配额（MB）',
               existing_server_default=sa.text('100'))
    op.alter_column('system_settings', 'orphan_retention_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='孤儿文件宽限期（天），到期自动物理删除',
               existing_server_default=sa.text('7'))
    op.alter_column('system_settings', 'federation_sync_interval_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='联邦 profile 同步间隔（分钟），默认 720（12小时）',
               existing_server_default=sa.text('720'))
    op.alter_column('system_settings', 'default_platform_credit',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='全局默认平台赠送额度（0=禁用）',
               existing_server_default=sa.text('0'))
    op.alter_column('system_settings', 'default_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'en'::character varying"))
    op.create_index('idx_system_logs_type', 'system_logs', ['log_type'], unique=False)
    op.create_index('idx_system_logs_created_at', 'system_logs', ['created_at'], unique=False)
    op.create_index('idx_rough_memories_owner', 'rough_memories', ['owner_type', 'owner_id'], unique=False)
    op.alter_column('rough_memories', 'value_score',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='记忆价值评分: 1=低价值(自动提取), 5=正常, 10=高价值',
               existing_nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('rough_memories', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='active | pending_archive | discarded',
               existing_nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('rough_memories', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rough_memories', 'owner_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('redemption_codes', 'is_api_pool',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否使用 API 池额度',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('redemption_codes', 'max_usage',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='此码最多可用多少 credit（NULL=一次性全额）',
               existing_nullable=True)
    op.alter_column('redemption_codes', 'note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='管理员备注（不暴露给用户）',
               existing_nullable=True)
    op.alter_column('redemption_codes', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('redemption_codes', 'code_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'ai_quota'::character varying"))
    op.create_index('idx_pending_msg_group', 'pending_messages', ['agent_id', 'group_id', 'is_read'], unique=False)
    op.create_index('idx_pending_msg_agent', 'pending_messages', ['agent_id', 'is_read'], unique=False)
    op.alter_column('pending_messages', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pending_messages', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pending_messages', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('idx_opencli_log_agent_time', 'opencli_usage_log', ['agent_id', 'executed_at'], unique=False)
    op.alter_column('opencli_command_whitelist', 'default_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index('idx_messages_group_id', 'messages', ['group_id'], unique=False)
    op.create_index('idx_messages_created_at', 'messages', ['created_at'], unique=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'sender_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('messages', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('instance_config', 'github_token_encrypted',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('groups', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('groups', 'owner_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('group_message_embeddings', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('group_message_embeddings', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('idx_group_invitations_invitee', 'group_invitations', ['invitee_id', 'status'], unique=False)
    op.create_index('idx_group_invitations_group', 'group_invitations', ['group_id'], unique=False)
    op.create_foreign_key('friendships_user_id_fkey', 'friendships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_friendship', 'friendships', type_='unique')
    op.drop_index(op.f('ix_friendships_user_id'), table_name='friendships')
    op.create_index('idx_friends_user', 'friendships', ['user_id'], unique=False)
    op.create_unique_constraint('friendships_user_id_friend_type_friend_id_key', 'friendships', ['user_id', 'friend_type', 'friend_id'])
    op.alter_column('friendships', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key('friendship_requests_requester_id_fkey', 'friendship_requests', 'users', ['requester_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_friendship_requests_requester_id'), table_name='friendship_requests')
    op.create_index('idx_fr_target', 'friendship_requests', ['target_type', 'target_id', 'status'], unique=False)
    op.create_index('idx_fr_requester', 'friendship_requests', ['requester_id', 'status'], unique=False)
    op.alter_column('friendship_requests', 'requester_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('idx_file_refs_ref', 'file_references', ['referrer_type', 'referrer_id'], unique=False)
    op.create_index('idx_file_refs_file', 'file_references', ['file_id'], unique=False)
    op.create_index('idx_file_metadata_path', 'file_metadata', ['path'], unique=False)
    op.create_index('idx_file_metadata_owner', 'file_metadata', ['owner_type', 'owner_id'], unique=False)
    op.alter_column('file_metadata', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('file_metadata', 'owner_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('file_metadata', 'path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_file_collab', 'file_collaborators', type_='unique')
    op.create_index('idx_file_collabs_file', 'file_collaborators', ['file_id'], unique=False)
    op.create_unique_constraint('file_collaborators_file_id_collaborator_type_collaborator_i_key', 'file_collaborators', ['file_id', 'collaborator_type', 'collaborator_id'])
    op.alter_column('federation_peers', 'url_rotation_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('federation_peers', 'shared_secret_encrypted',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_fed_entity_peer_local', 'federated_entities', type_='unique')
    op.drop_index(op.f('ix_federated_entities_federated_id'), table_name='federated_entities')
    op.create_unique_constraint('federated_entities_peer_id_entity_type_local_ref_id_key', 'federated_entities', ['peer_id', 'entity_type', 'local_ref_id'])
    op.create_unique_constraint('federated_entities_federated_id_key', 'federated_entities', ['federated_id'])
    op.drop_constraint('uq_dm_session_users', 'dm_sessions', type_='unique')
    op.create_unique_constraint('dm_sessions_user1_id_user2_id_key', 'dm_sessions', ['user1_id', 'user2_id'])
    op.create_index('idx_dm_messages_session', 'dm_messages', ['session_id'], unique=False)
    op.create_index('idx_dm_messages_created_at', 'dm_messages', ['created_at'], unique=False)
    op.alter_column('detail_memories', 'rough_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('conversation_log_config', 'compression_threshold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('60'))
    op.alter_column('conversation_log_config', 'default_delay_reply_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('api_usage_log', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='来源：user_key | pool_key',
               existing_nullable=False,
               existing_server_default=sa.text("'user_key'::character varying"))
    op.alter_column('api_usage_log', 'pool_key_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='使用的池 Key（NULL=用户自有 Key）',
               existing_nullable=True)
    op.alter_column('api_usage_log', 'agent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='哪个 AI 产生的调用',
               existing_nullable=True)
    op.alter_column('api_usage_log', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='哪个用户消耗的',
               existing_nullable=False)
    op.alter_column('api_key_pool', 'provider_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='关联 provider_config[].name，NULL=使用第一个/默认供应商',
               existing_nullable=True)
    op.alter_column('api_key_pool', 'concurrent_limit',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='并发上限，NULL=按模型默认(pro=500,flash=2500)',
               existing_nullable=True)
    op.alter_column('api_key_pool', 'priority',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='越高越优先分配',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('api_key_pool', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='管理员可禁用',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('api_key_pool', 'api_key_encrypted',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Fernet 加密的 API Key',
               existing_nullable=False)
    op.alter_column('api_key_pool', 'api_base_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='API 地址，NULL=继承全局',
               existing_nullable=True)
    op.alter_column('api_key_pool', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='管理员命名（如 DeepSeek 主号）',
               existing_nullable=False)
    op.drop_index(op.f('ix_ai_conversation_logs_created_at'), table_name='ai_conversation_logs')
    op.drop_index(op.f('ix_ai_conversation_logs_agent_id'), table_name='ai_conversation_logs')
    op.create_index('idx_conv_logs_time', 'ai_conversation_logs', ['created_at'], unique=False)
    op.create_index('idx_conv_logs_agent', 'ai_conversation_logs', ['agent_id'], unique=False)
    op.alter_column('agents', 'status_color',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='状态文字颜色(hex)',
               existing_nullable=True)
    op.alter_column('agents', 'status_text',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='自定义状态文本',
               existing_nullable=True)
    op.alter_column('agents', 'bio',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='AI 简介',
               existing_nullable=True)
    op.alter_column('agents', 'memory_shared_scope',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'private_only'::character varying"))
    op.alter_column('agents', 'memory_recent_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'memory_load_mode',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'index_only'::character varying"))
    op.alter_column('agents', 'group_owner_pays',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='群聊中 AI 消息是否由群主付费',
               existing_server_default=sa.text('true'))
    op.alter_column('agents', 'quota_whitelist',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_comment='不消耗配额的白名单实体列表',
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agents', 'auto_reset_quota',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='每次用户 DM 时自动重置配额计数',
               existing_server_default=sa.text('false'))
    op.alter_column('agents', 'disallow_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment=None,
               existing_comment='禁止时的模式: strict | own_key',
               existing_server_default=sa.text("'strict'::character varying"))
    op.alter_column('agents', 'others_chat_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='当前已使用次数（可重置）',
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'others_chat_quota',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='配额上限（触发次数），仅 quota 模式生效',
               existing_server_default=sa.text('30'))
    op.alter_column('agents', 'others_chat_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment=None,
               existing_comment='允许时的模式: unlimited | quota',
               existing_server_default=sa.text("'unlimited'::character varying"))
    op.alter_column('agents', 'allow_others_chat',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='是否允许非主人触发此 AI 对话',
               existing_server_default=sa.text('true'))
    op.alter_column('agents', 'ai_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'resonance'::character varying"))
    op.alter_column('agents', 'discoverable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='是否允许他人发现与查找此 AI',
               existing_server_default=sa.text('true'))
    op.alter_column('agents', 'auto_respond_friend_request',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='收到好友申请时是否自动触发 API 响应',
               existing_server_default=sa.text('false'))
    op.alter_column('agents', 'allow_friend_requests',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='是否允许接收好友申请',
               existing_server_default=sa.text('true'))
    op.alter_column('agents', 'hide_ai_identity',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('agents', 'reminder_grace',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'5m_after'::character varying"))
    op.alter_column('agents', 'max_alarms',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('agents', 'force_alarm_on_end',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('agents', 'alarm_max_tool_rounds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('agents', 'max_tool_rounds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('agents', 'delay_reply_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='延迟回复功能开关，NULL=继承全局默认',
               existing_nullable=True)
    op.alter_column('agents', 'api_credit_cost',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'config_profile',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'custom'::character varying"))
    op.alter_column('agents', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agent_user_configs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_user_configs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_agent_skills_agent', 'agent_skills', ['agent_id'], unique=False)
    op.alter_column('agent_skills', 'priority',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='优先级：数字越大越靠后',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_skills', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='技能配置JSON，各type不同schema',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_skills', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('agent_skills', 'skill_type',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='delay_reply | typing_indicator | scene_trigger | inject_prompt',
               existing_nullable=False)
    op.alter_column('agent_skills', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='技能名称，如「延迟回复」「温柔模式」',
               existing_nullable=False)
    op.alter_column('agent_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='快照时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_metrics', 'snapshot_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='指标快照数据',
               existing_nullable=False)
    op.alter_column('agent_config_history', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_agent_collaborator', 'agent_collaborators', type_='unique')
    op.create_unique_constraint('agent_collaborators_agent_id_user_id_key', 'agent_collaborators', ['agent_id', 'user_id'])
    op.create_table('agent_workspace',
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_task', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_task_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('interrupted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('interruption_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('todo', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('plan', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('journal', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='agent_workspace_agent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', name='agent_workspace_pkey')
    )
    op.create_table('agent_alarms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wake_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('task', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('fired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'fired'::character varying, 'cancelled'::character varying]::text[])", name='agent_alarms_status_check'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='agent_alarms_agent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='agent_alarms_pkey')
    )
    op.create_table('structured_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sub_key', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('field', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='structured_records_agent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='structured_records_pkey'),
    sa.UniqueConstraint('agent_id', 'category', 'sub_key', 'field', name='structured_records_agent_id_category_sub_key_field_key')
    )
    op.drop_table('personality_anchors')
    op.drop_table('agent_triggers')
    op.drop_table('agent_state_stack')
    op.drop_table('agent_skill_relations')
    op.drop_table('agent_configs')
    op.drop_table('agent_attention')
    # ### end Alembic commands ###
